services:
  backend:
    image: open-ai-canvas-backend:server
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        GOPROXY: ${GOPROXY:-https://proxy.golang.org,direct}

  web:
    image: open-ai-canvas-web:server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SELF_HOSTED_MODE: ${SELF_HOSTED_MODE:-false}
